version: '3'

services:
  telegram_notify_dev:
    container_name: telegram_notify_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes:
      - .:/extension
    env_file:
      - .telegram_notify_dev.env

  telegram_notify_bash:
    container_name: telegram_notify_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .telegram_notify_dev.env

  telegram_notify_test:
    container_name: telegram_notify_test
    build:
      context: .
    working_dir: /extension
    command: /bin/bash -c "poetry install && poetry run flake8 && poetry run pytest"
    volumes:
      - .:/extension
    env_file:
      - .telegram_notify_dev.env
